Repository jenkinsci/confluence-publisher-plugin, pull requests merged in 2021-11, with the labels that each got.

#19 Miscellaneous code cleanup
  src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluencePublisher.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSession.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/editors/AfterTokenEditor.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/editors/BeforeTokenEditor.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/editors/BetweenTokensEditor.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/editors/MarkupEditor.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/generators/FileGenerator.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/generators/MarkupGenerator.java
  src/main/java/com/myyearbook/hudson/plugins/confluence/wiki/generators/PlainTextGenerator.java
  src/test/java/com/myyearbook/hudson/plugins/confluence/wiki/editors/BetweenTokensEditorTest.java
Labels: enhancement

#20 Create dependabot.yml
  .github/dependabot.yml
Labels: chore

#18 Enable automatic release on merge to master
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/draft.yml
  pom.xml
Labels: chore

#23 fix changelist format
  .mvn/maven.config
Labels: skip-changelog
